---
version: 2.1

orbs:
  do: twdps/pipeline-events@3.2.3
  op: twdps/onepassword@2.0.2

globals:
  - &context empc-lab
  - &executor-image cimg/go:1.21.4

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /^[0-9]+\.[0-9]+\.[0-9]+$/

executors:
  go-builder:
    docker:
      - image: *executor-image

jobs:

  static code analysis:
    description: golang static code analysis
    executor: go-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: golang lint
          command: golangci-lint run ./...
      - run:
          name: check
          command: exit 1

workflows:

  development build and test:
    jobs:
    - static code analysis:
        context: *context
        filters: *on-push-main