---
version: 2.1

orbs:
  do: twdps/pipeline-events@3.2.3
  op: twdps/onepassword@2.0.2

globals:
  - &context empc-lab
  - &executor-image cimg/go:1.21.4

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /^[0-9]+\.[0-9]+\.[0-9]+$/

executors:
  go-builder:
    docker:
      - image: *executor-image

commands:

  set-environment:
    steps:
      - op/packages:
          op-version: 2.24.0-1
      - op/env
      - op/tpl:
          out-path: cmd
          out-file: config.go
      - op/write:
          op-value: empc-lab/svc-cosign-private-key/notesPlain
          out-file: cosign.key
      - op/write:
          op-value: empc-lab/svc-cosign-public-key/notesPlain
          out-file: cosign.pub

jobs:

  static code analysis:
    description: golang static code analysis
    executor: go-builder
    steps:
      - checkout
      - setup_remote_docker
      - set-environment
      - run:
          name: golang lint
          command: golangci-lint run ./...
      - run:
          name: secure practices scan
          command: |
            curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.18.2
            gosec -exclude=G104 ./...
      - run:
          name: build test
          command: |
            go mod tidy
            go build
      - run:
          name: cli build smoketest
          command: |
            set -exo pipefail
            ./pskctl version | grep "snapshot"

  release-version:
    description: publish release version
    executor: go-builder
    steps:
      - checkout
      - setup_remote_docker
      - set-environment
      - run:
          name: goreleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:

  development build and test:
    jobs:
    - static code analysis:
        context: *context
        filters: *on-push-main

    - release-version:
        context: *context
        requires:
          - static code analysis